"""initial migration

Revision ID: 3712609d63a7
Revises:
Create Date: 2025-08-14 00:10:51.939438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3712609d63a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # IMPORTANT: All op.drop_index() and op.drop_constraint() lines have been removed.
    # For an initial migration, you should only be creating tables, indexes, and constraints.

    # Assuming your op.create_table commands (which are typically generated first) are implicitly present.
    # Example (these lines would be generated by alembic, do NOT add them manually unless they are missing)
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=255), nullable=False),
    # sa.Column('hashed_password', sa.String(length=255), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.Column('is_admin', sa.Boolean(), nullable=True),
    # sa.Column('is_verified', sa.Boolean(), nullable=True),
    # sa.Column('university', sa.String(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('favorites',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('listing_id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # # ... and so on for all your tables: listings, messages, notifications, verifications

    # Create indexes and constraints:
    op.create_index(op.f('ix_favorites_listing_id'), 'favorites', ['listing_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)

    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)

    op.create_index(op.f('ix_messages_listing_id'), 'messages', ['listing_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)

    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)

    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.alter_column('verifications', 'university_email',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('verifications', 'student_id',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)

    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_index(op.f('ix_verifications_user_id'), 'verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_user_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.create_unique_constraint(op.f('verifications_user_id_key'), 'verifications', ['user_id'])
    op.create_index(op.f('ix_verifications_user'), 'verifications', ['user_id'], unique=False)
    op.alter_column('verifications', 'student_id',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('verifications', 'university_email',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_listing_id'), table_name='messages')
    op.create_index(op.f('ix_messages_sender'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_listing'), 'messages', ['listing_id'], unique=False)
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.create_index(op.f('ix_listings_owner'), 'listings', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_listing_id'), table_name='favorites')
    op.create_index(op.f('ix_favorites_user'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_listing'), 'favorites', ['listing_id'], unique=False)
    # ### end Alembic commands ###