"""Add otp_expires_at to verifications table

Revision ID: 8a1f6b620151
Revises: e7648e14c010
Create Date: 2025-08-13 16:41:12.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.a
revision = '8a1f6b620151'
down_revision = 'e7648e14c010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ... other auto-generated commands
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'otp_expires_at')
    # ... other auto-generated commands
    # ### end Alembic commands ###