"""Ensure all timestamps are timezone aware

Revision ID: bc301572f4ed
Revises: fa3276aca21d
Create Date: 2025-08-13 17:31:24.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'bc301572f4ed'
down_revision = 'fa3276aca21d' # IMPORTANT: Replace with the actual previous revision ID
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter otp_expires_at to be timezone aware
    op.alter_column(
        'verifications',
        'otp_expires_at',
        existing_type=sa.TIMESTAMP(), # Assuming it was TIMESTAMP WITHOUT TIME ZONE
        type_=sa.DateTime(timezone=True),
        nullable=True, # Keep its existing nullability
        postgresql_using='otp_expires_at::timestamp with time zone' # Cast existing data
    )

    # Alter created_at to be timezone aware with CURRENT_TIMESTAMP default
    op.alter_column(
        'verifications',
        'created_at',
        existing_type=sa.TIMESTAMP(), # Assuming it was TIMESTAMP WITHOUT TIME ZONE
        type_=sa.DateTime(timezone=True),
        nullable=False, # Keep its existing nullability
        server_default=sa.text('CURRENT_TIMESTAMP'), # Set server-side default
        postgresql_using='created_at::timestamp with time zone' # Cast existing data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert created_at to be timezone naive and remove server default
    op.alter_column(
        'verifications',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        nullable=False,
        server_default=None # Remove server-side default
    )

    # Revert otp_expires_at to be timezone naive
    op.alter_column(
        'verifications',
        'otp_expires_at',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        nullable=True
    )
    # ### end Alembic commands ###
