"""Add otp_code to verifications table

Revision ID: e7648e14c010
Revises: 6460ebb5c94f
Create Date: 2025-08-13 16:41:12.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.a
revision = 'e7648e14c010'
down_revision = '6460ebb5c94f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('otp_code', sa.String(), nullable=True))
    # ... other auto-generated commands
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'otp_code')
    # ... other auto-generated commands
    # ### end Alembic commands ###