"""Update created_at default to be timezone aware

Revision ID: fa3276aca21d
Revises: 8ce389ab0342
Create Date: 2025-08-13 17:31:24.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'fa3276aca21d'
down_revision = '8ce389ab0342'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'verifications', 
        'created_at',
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'verifications', 
        'created_at',
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False
    )
    # ### end Alembic commands ###